baseURL: "https://yoshizumi.tech/"
languageCode: "jp"
title: "yoshizumi.tech"
theme:
  - "PaperMod"

# 新しい設定
params:
  customCSS: ["css/custom.css"]
  social:
    - name: "twitter"
      url: "https://twitter.com/yourprofile"
    - name: "github"
      url: "https://github.com/yourprofile"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  customCSS: ["css/custom.css"]
